FROM ubuntu:18.04

ARG POSTGRES_VERSION=11

RUN apt-get update \
 && apt-get install -y curl gnupg2 \
 && echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
 && curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential \
      postgresql-${POSTGRES_VERSION} \
      postgresql-server-dev-${POSTGRES_VERSION} \
      ruby \
      sudo \
 && apt-get clean \
 && rm -Rf /var/lib/apt/lists/*

RUN sudo /etc/init.d/postgresql restart \
 && sudo -u postgres createuser -s root

COPY Makefile /app/
RUN make -C app protoc

COPY *.hpp *.cpp *.rb *.sh *.sql *.control *.md /app/
COPY /test_protos /app/test_protos
