name: Tests on PG15

on: [push]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests in Docker
      run: env USE_DOCKER=1 POSTGRES_VERSION=15 ./build-and-test.sh
